### ISSUE TITLE
Mobile website

### ISSUE THREAD

**Issue by ghost** [theQRL/QRL#1160] opened 2018-04-02 08:55 UTC
You guys should make the wallet website mobile friendly

**Comment by cyyber** [comment] 2018-04-03 20:36
Issue related to https://github.com/theQRL/qrl-wallet
@scottdonaldau

**Comment by scottdonaldau** [comment] 2018-04-03 22:07
Duplicate of https://github.com/theQRL/qrl-wallet/issues/40

**Closed as completed by scottdonaldau** 2018-04-03 22:07 UTC
