### ISSUE TITLE
[qrl wallet_ls] No wallet found at /xxx/xxx  

### ISSUE THREAD

**Issue by converghub** [theQRL/QRL#708] opened 2017-12-11 07:59 UTC
when you use "qrl wallet_ls",  it works only when you are in the "$HOME/.qrl/wallet".
```
pi@raspberrypi:~ $ qrl wallet_ls
No wallet found at /home/pi
pi@raspberrypi:~ $ cd .qrl/wallet/
pi@raspberrypi:~/.qrl/wallet $ qrl wallet_ls
Wallet at          : /home/pi/.qrl/wallet
Number  Address                                                                    Balance
-----------------------------------------------------------------------------------------------
0       Q1f009c3b5edef18531904e3d8c40ef108639f565f820751dcdf2970227cd264116165e04  100.00000000
```
Here is my pi3's information.
```
pi@raspberrypi:~ $ lsb_release -a
No LSB modules are available.
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 9.1 (stretch)
Release:        9.1
Codename:       stretch
```

**Comment by jleni** [comment] 2018-04-07 07:42
This is a duplicate of #709

**Closed as completed by jleni** 2018-04-07 07:42 UTC
Labels: Type: Question, Priority: Low, Priority: Medium, CLI
